#!/bin/sh
#
# WWW::Quvi
# Copyright (C) 2011  Toni Gundogdu <legatvs@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#

# wqwrap - WWW::Quvi wrapper script

note()
{
  echo "Run in the top source directory of WWW::Quvi.
Make sure you have run 'perl Makefile.PL ; make' first."
  exit 0
}

usage()
{
  echo "Usage: $0 [perl-script]
Example: $0 examples/website.pl"
  note
}

[ $# -lt  1 ] && usage

([ -d lib ] && [ -d blib ]) || note

export PERL5LIB=$PERL5LIB:`pwd`/lib
export PERL5LIB=$PERL5LIB:`pwd`/blib/arch/auto/WWW/Quvi
#echo $PERL5LIB

perl $@

# vim: set ts=2 sw=2 tw=72 expandtab:
